config/routes.rb
Rails.application.routes.draw do
  root to: 'map#index'

  get "/search" => "map#search", as: :search

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    results = Geocoder.search "Houston"
    @lat = results.first.geometry["location"]["lat"].to_f
    @lng = results.first.geometry["location"]["lng"].to_f
  end

  def search
    @search = params[:body].strip

    results = Geocoder.search @search
    if results.first.geometry["location"]["lat"].to_f
      @lat = results.first.geometry["location"]["lat"].to_f
      @lng = results.first.geometry["location"]["lng"].to_f
      render :index
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maps</title>

  <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css" />
  <script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

    <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <ul class="nav navbar-nav navbar-right">
          <li><%= link_to root_path, class: "brand", style:"font-size: 2rem;" do%>
            <span class="glyphicon glyphicon-globe" ></span>
            Mapper
          <% end %></li>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= form_tag(search_path, {class: "navbar-form navbar-left", method: :get}) do %>
        <div class="form-group has-feedback">
          <%= text_field_tag :body, params[:body], placeholder: 'Search', class: "form-control input-lg"%>
          <span class="glyphicon glyphicon-search form-control-feedback"></span>
        </div>
      <% end %>
    </div>
  </div>
</nav>

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/map/index.html.erb
<div id="map"></div>

<div id="foo" data-lat="<%= @lat %>"></div>
<div id="boo" data-lng="<%= @lng %>"></div>